/**
 * pythonParser.js
 *
 * Converts Python UI code (the format generated by PyUI Builder, plus simple
 * hand written tkinter/customtk code) into a "widget tree" that can be loaded
 * onto the canvas.
 *
 * Parsed node shape:
 * {
 *   variable: "button_1",        // python variable name
 *   widgetType: "button",        // static widgetType of the canvas widget class
 *   parentVariable: "main",      // python variable of the parent widget
 *   attrs: { "buttonLabel": "Click me", "styling.backgroundColor": "#E4E2E2" },
 *   size: { width, height },     // optional (from place())
 *   pos: { x, y },               // optional (from place())
 *   layout: { type: "place"|"flex"|"grid", ...args },
 *   children: [],
 * }
 */


/**
 * Builds a map of widgetType -> widget class from a sidebar widgets array.
 * @param {Array} sidebarWidgets - e.g. TkinterWidgets / CustomTkWidgets
 * @returns {Object} e.g. { label: Label, button: Button, ... }
 */
export function buildWidgetTypeRegistry(sidebarWidgets = []) {
    const registry = {}
    for (const item of sidebarWidgets) {
        const widgetClass = item.widgetClass
        if (widgetClass && widgetClass.widgetType) {
            registry[widgetClass.widgetType] = widgetClass
        }
    }
    return registry
}


// python widget class name -> canvas widgetType (works for both tkinter + customtk)
const CLASS_TO_WIDGET_TYPE = {
    "Tk": "main_window",
    "CTk": "main_window",
    "Toplevel": "toplevel",
    "CTkToplevel": "toplevel",
    "Frame": "frame",
    "CTkFrame": "frame",
    "LabelFrame": "label_frame",
    "Label": "label",
    "CTkLabel": "label",
    "Button": "button",
    "CTkButton": "button",
    "Entry": "entry",
    "CTkEntry": "entry",
    "Text": "Text",
    "CTkTextbox": "Text",
    "Checkbutton": "check_button",
    "CTkCheckBox": "check_button",
    "Radiobutton": "radio_button",
    "CTkRadioButton": "radio_button",
    "Scale": "scale",
    "CTkSlider": "scale",
    "OptionMenu": "option_menu",
    "CTkOptionMenu": "option_menu",
    "Spinbox": "spin_box",
    "CTkSpinbox": "spin_box",
    "Listbox": "listbox",
    "Message": "message",
    "PanedWindow": "paned_window",
    "Scrollbar": "scrollbar",
    "Progressbar": "progressbar",
    "Treeview": "treeview",
    "Notebook": "notebook",
    "Combobox": "combobox",
    "Separator": "separator",
    "Menu": "menu_bar",
    "Menubutton": "menu_bar",
    "Canvas": "canvas",
    "Sizegrip": "sizegrip",

    // custom teaching widgets (names used by the widget classes in this builder)
    "SliderValue": "slider_value",
    "Counter": "counter",
    "Stopwatch": "stopwatch",
    "TodoList": "todo_list",
    "ColorPicker": "color_picker",
    "TemperatureConverter": "temperature_converter",
    "PasswordEntry": "password_entry",
    "Listbox": "listbox",
    "Progressbar": "progressbar",
    "Combobox": "combobox",
}


// maps python kwargs to the attr paths used by the canvas widget classes.
// Widgets not listed here fall back to a generic mapping (see getWidgetTypeAttrMapping)
const WIDGET_ATTR_MAP = {
    label: {
        text: "labelWidget",
        image: "imageUpload",
    },
    button: {
        text: "buttonLabel",
    },
    entry: {
        placeholder: "placeHolder",
        show: "show", // password entry
    },
    check_button: {
        text: "checkLabel",
        variable: null, // skip control variables
        onvalue: null,
        offvalue: null,
    },
    radio_button: {
        text: null, // handled via radios group below
        value: null,
        variable: null,
    },
    spin_box: {
        from_: "spinProps.min",
        to: "spinProps.max",
        increment: "spinProps.step",
        value: "spinProps.default",
    },
    scale: {
        from_: "min",
        to: "max",
        variable: null,
        orient: null,
    },
    option_menu: {
        value: "defaultValue",
    },
    main_window: {
        title: "title",
    },
    combobox: {
        values: "options",
        textvariable: null,
    },
    listbox: {
        listvariable: null,
    },
    progressbar: {
        maximum: "max",
        value: "value",
        mode: "mode",
        orient: null,
    },
}


// generic styling python kwargs -> canvas attr path
const STYLING_ATTR_MAP = {
    bg: "styling.backgroundColor",
    background: "styling.backgroundColor",
    fg: "styling.foregroundColor",
    foreground: "styling.foregroundColor",
    relief: "styling.relief",
    bd: "styling.borderWidth",
    borderwidth: "styling.borderWidth",
    width: "styling.width",
    height: "styling.height",
    font: "styling.fontFamily",
    cursor: "styling.cursor",
    padx: "padding.padX",
    pady: "padding.padY",
}


function unquote(str) {
    if (typeof str !== "string") return str
    str = str.trim()
    if ((str.startsWith('"') && str.endsWith('"')) || (str.startsWith("'") && str.endsWith("'"))) {
        return str.slice(1, -1)
    }
    return str
}


function toNumber(str) {
    if (typeof str !== "string") return str
    const trimmed = str.trim()
    if (trimmed === "") return str
    if (/^-?\d+(\.\d+)?$/.test(trimmed)) return Number(trimmed)
    return str
}


/**
 * Parses a python literal-ish value into a JS value.
 * Handles strings, numbers, booleans, None, tuples/lists, and simple identifiers
 * such as tk.TOP, True, "x".
 */
export function parsePythonValue(raw) {
    if (raw === undefined || raw === null) return raw
    let value = String(raw).trim()

    if (value === "True") return true
    if (value === "False") return false
    if (value === "None") return null

    // strings
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        // handle the last char being escaped quote
        return unquote(value)
    }

    // lists / tuples -> array
    if ((value.startsWith("[") && value.endsWith("]")) ||
        (value.startsWith("(") && value.endsWith(")"))) {
        const inner = value.slice(1, -1)
        if (inner.trim() === "") return []
        return splitTopLevel(inner).map(parsePythonValue)
    }

    // numbers
    const numeric = toNumber(value)
    if (typeof numeric === "number") return numeric

    // identifiers like tk.TOP, "x" (already quoted) -> return the raw name
    if (/^[a-zA-Z_][a-zA-Z0-9_.]*$/.test(value)) {
        return value
    }

    // fallback: strip quotes
    return unquote(value)
}


/**
 * Splits a python argument string on top-level commas (respects nesting + quotes)
 */
export function splitTopLevel(str) {
    const parts = []
    let depth = 0
    let current = ""
    let quote = null

    for (let i = 0; i < str.length; i++) {
        const char = str[i]

        if (quote) {
            current += char
            if (char === quote && str[i - 1] !== "\\") {
                quote = null
            }
            continue
        }

        if (char === '"' || char === "'") {
            quote = char
            current += char
        } else if (char === "(" || char === "[" || char === "{") {
            depth++
            current += char
        } else if (char === ")" || char === "]" || char === "}") {
            depth--
            current += char
        } else if (char === "," && depth === 0) {
            parts.push(current.trim())
            current = ""
        } else {
            current += char
        }
    }

    if (current.trim() !== "") {
        parts.push(current.trim())
    }

    return parts
}


/**
 * Parses the arguments inside a python function call: "master=main, text=\"hi\"".
 * Returns { positionals: [], kwargs: {key: value} } where value is a parsed JS value.
 * Kwarg values that look like variable references (e.g. equation_var) are returned as strings.
 */
export function parsePythonArgs(argsStr) {
    const result = { positionals: [], kwargs: {} }

    for (const rawArg of splitTopLevel(argsStr || "")) {
        if (!rawArg) continue

        // kwargs
        const eqIndex = findTopLevelEquals(rawArg)
        if (eqIndex !== -1) {
            const key = rawArg.slice(0, eqIndex).trim()
            const rawValue = rawArg.slice(eqIndex + 1).trim()

            // star args like *options -> skip
            if (key.startsWith("*")) {
                result.positionals.push(rawValue)
                continue
            }

            if (key.startsWith("**")) continue

            // don't convert values that reference other widgets / variables
            // (textvariable=foo, command=bar, variable=baz)
            if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(rawValue) && !/^(True|False|None|\d+)$/.test(rawValue)) {
                result.kwargs[key] = rawValue // keep as a string reference
            } else {
                result.kwargs[key] = parsePythonValue(rawValue)
            }
            continue
        }

        // positional
        result.positionals.push(parsePythonValue(rawArg))
    }

    return result
}


function findTopLevelEquals(str) {
    let depth = 0
    let quote = null
    for (let i = 0; i < str.length; i++) {
        const char = str[i]
        if (quote) {
            if (char === quote && str[i - 1] !== "\\") quote = null
            continue
        }
        if (char === '"' || char === "'") {
            quote = char
        } else if (char === "(" || char === "[" || char === "{") {
            depth++
        } else if (char === ")" || char === "]" || char === "}") {
            depth--
        } else if (char === "=" && depth === 0) {
            return i
        }
    }
    return -1
}


/**
 * Combines the args from a constructor call + a config() call into a flat
 * attr mapping for a canvas widget.
 */
function buildWidgetAttrs(widgetType, constructorArgs, configArgs) {
    const attrs = {}
    const attrMap = WIDGET_ATTR_MAP[widgetType] || {}

    const applyArgs = (args, fromConfig) => {
        for (const [key, value] of Object.entries(args)) {
            if (value === null || value === undefined) continue

            // styling properties
            const stylingPath = STYLING_ATTR_MAP[key]
            if (stylingPath) {
                if (key === "font" && Array.isArray(value)) {
                    attrs[stylingPath] = value[0] || "Arial"
                } else if (key === "font" && typeof value === "string") {
                    attrs[stylingPath] = value
                } else {
                    attrs[stylingPath] = value
                }
                continue
            }

            // widget-specific mapping
            const mapped = attrMap[key]
            if (mapped === null) continue // explicitly skipped (control vars etc)
            if (mapped) {
                attrs[mapped] = value
                continue
            }

            // unknown keys: keep the key as-is (safest default)
            attrs[key] = value
        }
    }

    applyArgs(constructorArgs)
    applyArgs(configArgs)

    return attrs
}


/**
 * Converts the side/fill/expand of a pack() call into flexManager attrs.
 */
function packToFlexAttrs(args) {
    const attrs = {}
    const side = (args.side || "top")
    attrs["flexManager.side"] = typeof side === "string" ? side.replace("tk.", "").toLowerCase() : "top"

    if (args.fill) {
        const fill = String(args.fill).replace(/"/g, "")
        attrs["flexManager.fillX"] = fill === "x" || fill === "both"
        attrs["flexManager.fillY"] = fill === "y" || fill === "both"
    }
    if (args.expand) {
        attrs["flexManager.expand"] = true
    }
    if (args.anchor) {
        attrs["flexManager.anchor"] = String(args.anchor).replace(/"/g, "")
    }
    return attrs
}


/**
 * Main entry: parses a python UI code string into an array of widget nodes.
 */
export function parsePythonToWidgetTree(code) {
    if (!code) return []

    const lines = code.split("\n")
    const widgets = []          // flat list of parsed widget nodes
    const widgetByVariable = {} // variable -> node
    let insideDef = 0           // skip helper function bodies
    let rootVariable = ""

    // composite widgets (counter, slider with value, stopwatch, todo list,
    // color picker, temperature converter) emit helper defs like
    // `def counter_increment():` and `def slider_1_show_value(value):`.
    // Collect that evidence so we can merge their sub-widgets back into a
    // single canvas widget.
    const compositeDefs = new Set()

    const compositeWidgetTypes = ["counter", "slider_value", "stopwatch", "todo_list", "color_picker", "temperature_converter"]

    // helper used by the creation/var handlers to detect composite widgets
    // from the helper defs that were collected
    const findCompositeOwnerNode = (variable) => {
        if (typeof variable !== "string") return null

        const base = variable.replace(/_(var|value_var)$/, "")
        if (!base) return null

        // 1) if a composite node with this base already exists (e.g. `counter`
        //    created from `counter_var = tk.IntVar(...)`), return it.
        const existing = widgetByVariable[base]
        if (existing) return existing

        // 2) if the variable is a sub-widget of an existing composite
        //    (e.g. `counter_label` -> `counter`), route to the composite.
        const prefixOwner = widgets.find(w =>
            w !== null &&
            compositeWidgetTypes.includes(w.widgetType) &&
            variable.startsWith(w.variable + "_")
        )
        if (prefixOwner) return prefixOwner

        // 3) create a composite node from the helper def evidence
        //    (e.g. `def counter_increment():` -> counter widget named `counter`)
        const hasDef = (suffix) => Array.from(compositeDefs).some(d => d.startsWith(base + suffix))

        let type = null
        if (hasDef("_increment")) type = "counter"
        else if (hasDef("_show_value") || hasDef("_update_value")) type = "slider_value"
        else if (hasDef("_start") || hasDef("_stop")) type = "stopwatch"
        else if (hasDef("_add_task") || hasDef("_remove_task")) type = "todo_list"
        else if (hasDef("_convert") || hasDef("_pick")) type = /temp/i.test(base) ? "temperature_converter" : "color_picker"

        if (!type) return null

        // create the composite node (parent resolved later from sub-widgets)
        const node = {
            variable: base,
            widgetType: type,
            parentVariable: "",
            attrs: {},
            children: [],
        }
        widgets.push(node)
        widgetByVariable[base] = node
        return node
    }

    // track the last assignment of each widget line so we can apply
    // `.config()` / `.place()` / `.pack()` / `.grid()` calls that follow
    const lastWidgetByVariable = {}

    for (let rawLine of lines) {
        const line = rawLine.trim()

        // track helper functions (def ...) so we can skip their bodies.
        // A def body is any indented line after the def; a non-indented,
        // non-blank line ends it (blank lines between functions are skipped).
        if (insideDef > 0 && line !== "" && !rawLine.startsWith(" ") && !rawLine.startsWith("\t")) {
            insideDef = 0 // back at top level
        }

        if (!line) continue

        if (/^def\s+\w+\(/.test(line)) {
            const defMatch = line.match(/^def\s+(\w+)\(/)
            if (defMatch) compositeDefs.add(defMatch[1])
            insideDef = line.endsWith(":") ? 1 : 0
            continue
        }
        if (insideDef > 0) {
            // inside a helper function body - skip everything (including for/if blocks)
            continue
        }

        // comments / imports / mainloop
        if (line.startsWith("#") || line.startsWith("import ") || line.startsWith("from ")) continue
        if (line.includes(".mainloop(")) continue
        if (line.includes(".update(")) continue

        // window methods: main.title(...), main.geometry(...), main.config(...), main.resizable(...)
        const windowMethod = line.match(/^(\w+)\.(title|geometry|resizable|minsize|maxsize|iconbitmap|iconphoto)\((.*)\)$/)
        if (windowMethod) {
            const [, variable, method, argsStr] = windowMethod
            const node = widgetByVariable[variable]
            if (node && node.widgetType === "main_window") {
                const args = parsePythonArgs(argsStr).kwargs
                if (method === "title") {
                    node.attrs["title"] = unquote(argsStr.trim())
                } else if (method === "geometry") {
                    const match = argsStr.match(/"(\d+)x(\d+)/)
                    if (match) {
                        node.size = { width: Number(match[1]), height: Number(match[2]) }
                    }
                } else if (method === "resizable") {
                    node.attrs["resizable"] = argsStr.trim()
                }
            }
            continue
        }

        // main.config(bg="#fff") or similar
        const windowConfig = line.match(/^(\w+)\.config\((.*)\)$/)
        if (windowConfig) {
            const [, variable, argsStr] = windowConfig
            const args = parsePythonArgs(argsStr).kwargs

            const existingNode = widgetByVariable[variable]
            if (existingNode && existingNode.widgetType === "main_window") {
                // apply bg only
                if (args.bg || args.background) {
                    existingNode.attrs["styling.backgroundColor"] = args.bg || args.background
                }
                continue
            }

            // a config call for a widget we created earlier
            const lastWidget = lastWidgetByVariable[variable]
            if (lastWidget) {
                const configAttrs = buildWidgetAttrs(lastWidget.widgetType, {}, args)
                Object.assign(lastWidget.attrs, configAttrs)
            }
            continue
        }

        // layout calls: variable.place(...) / .pack(...) / .grid(...)
        const layoutCall = line.match(/^(\w+)\.(place|pack|grid)\((.*)\)$/)
        if (layoutCall) {
            const [, variable, method, argsStr] = layoutCall
            const node = widgetByVariable[variable]
            if (!node) continue

            const args = parsePythonArgs(argsStr).kwargs

            if (method === "place") {
                node.layout = { type: "place" }
                if (args.x !== undefined) node.pos = { ...(node.pos || {}), x: Number(args.x) }
                if (args.y !== undefined) node.pos = { ...(node.pos || {}), y: Number(args.y) }
                if (args.width !== undefined) node.size = { ...(node.size || {}), width: Number(args.width) }
                if (args.height !== undefined) node.size = { ...(node.size || {}), height: Number(args.height) }
                if (args.relx !== undefined) node.pos = { ...(node.pos || {}), x: node.size?.width ? 0 : 0 }
            } else if (method === "pack") {
                node.layout = { type: "flex", ...packToFlexAttrs(args) }
            } else if (method === "grid") {
                node.layout = { type: "grid" }
                if (args.row !== undefined) node.attrs["gridManager.row"] = Number(args.row) + 1
                if (args.column !== undefined) node.attrs["gridManager.column"] = Number(args.column) + 1
                if (args.rowspan !== undefined) node.attrs["gridManager.rowSpan"] = Number(args.rowspan)
                if (args.columnspan !== undefined) node.attrs["gridManager.columnSpan"] = Number(args.columnspan)
                if (args.sticky !== undefined) node.attrs["gridManager.sticky"] = String(args.sticky).replace(/"/g, "")
            }
            continue
        }

        // window-level grid configuration: main.grid_rowconfigure / grid_columnconfigure
        if (/^(\w+)\.grid_(row|column)configure\(/.test(line)) continue

        // widget creation: variable = tk.Label(...) / ttk.Combobox(...) etc
        // note: control variables (tk.IntVar etc) must NOT match here, they're handled below
        const creation = line.match(/^(\w+)\s*=\s*(?:([a-zA-Z_][\w.]*)\.)?(IntVar|StringVar|DoubleVar|BooleanVar)\s*\((.*)\)$/)
            ? null
            : line.match(/^(\w+)\s*=\s*(?:([a-zA-Z_][\w.]*)\.)?([A-Z][\w]*)\s*\((.*)\)$/)
        if (creation) {
            const [, variable, modulePrefix, className, argsStr] = creation

            const widgetType = CLASS_TO_WIDGET_TYPE[className]
            if (!widgetType) continue

            const args = parsePythonArgs(argsStr)
            const positionals = args.positionals
            const kwargs = args.kwargs

            // parent variable: master=... or first positional
            let parentVariable = ""
            if (kwargs.master) {
                parentVariable = String(kwargs.master)
            } else if (positionals.length > 0 && typeof positionals[0] === "string" && positionals[0] !== "") {
                parentVariable = positionals[0]
            }

            // handle tk.Tk() / CTk() root
            if (widgetType === "main_window" && !rootVariable) {
                rootVariable = variable
            }

            // is this a sub-widget of a composite widget? (counter_label, slider_value_value_label)
            const compositeOwner = findCompositeOwnerNode(variable)
            if (compositeOwner) {
                // the composite node belongs to the same parent as its sub-widgets
                if (!compositeOwner.parentVariable && parentVariable) {
                    compositeOwner.parentVariable = parentVariable
                }
                // route the scale props to the composite slider node
                if (compositeOwner.widgetType === "slider_value") {
                    if (kwargs.from_ !== undefined) compositeOwner.attrs["min"] = kwargs.from_
                    if (kwargs.to !== undefined) compositeOwner.attrs["max"] = kwargs.to
                }
                if (compositeOwner.widgetType === "todo_list" && widgetType === "listbox") {
                    compositeOwner.attrs["options"] = ""
                }
                continue
            }

            const node = {
                variable,
                widgetType,
                parentVariable,
                attrs: buildWidgetAttrs(widgetType, kwargs, {}),
                children: [],
            }

            widgets.push(node)
            widgetByVariable[variable] = node
            lastWidgetByVariable[variable] = node
            continue
        }

        // variable = tk.IntVar(value=5) / StringVar / DoubleVar / BooleanVar
        const varCreation = line.match(/^(\w+)\s*=\s*(?:[a-zA-Z_][\w.]*\.)?(IntVar|StringVar|DoubleVar|BooleanVar)\((.*)\)$/)
        if (varCreation) {
            const [, variable, varType, argsStr] = varCreation
            const args = parsePythonArgs(argsStr).kwargs

            // composite widgets create vars like counter_var, slider_value_var
            const baseVariable = variable.replace(/_(var|value_var)$/, "")

            // counter: counter_var = tk.IntVar(value=0)  -> counter widget
            const compositeOwner = findCompositeOwnerNode(baseVariable)
            if (compositeOwner) {
                if (compositeOwner.widgetType === "counter" && args.value !== undefined) {
                    compositeOwner.attrs["initialValue"] = args.value
                } else if (compositeOwner.widgetType === "slider_value" && args.value !== undefined) {
                    compositeOwner.attrs["defaultValue"] = args.value
                } else if (compositeOwner.widgetType === "color_picker" && args.value !== undefined) {
                    compositeOwner.attrs["color"] = args.value
                }
                continue
            }

            // a plain control var used by an existing widget (e.g. entry, scale) - ignore
            continue
        }

    }

    // ---- post processing ----

    // set the composite node's parent from its sub-widgets
    for (const node of widgets) {
        if (["counter", "slider_value", "stopwatch", "todo_list", "color_picker", "temperature_converter"].includes(node.widgetType)) {
            const sub = widgets.find(w => w !== node && w.variable.startsWith(node.variable + "_"))
            if (sub && sub.parentVariable) {
                node.parentVariable = sub.parentVariable
            }
        }
    }

    const findCompositeOwner = (node) => {
        return widgets.find(w =>
            w !== node &&
            compositeWidgetTypes.includes(w.widgetType) &&
            node.variable.startsWith(w.variable + "_")
        )
    }

    const filtered = widgets.filter(node => {
        // helper widgets like counter_label, counter_minus, slider_value_value_label
        if (node.widgetType === "label" || node.widgetType === "button" || node.widgetType === "entry" || node.widgetType === "scale") {
            return !findCompositeOwner(node)
        }
        // radio buttons are emitted per-option as <var>_0, <var>_1 ... and belong
        // to a single radio_button widget - drop the sub widgets
        if (node.widgetType === "radio_button") {
            const owner = widgets.find(w =>
                w !== node &&
                w.widgetType === "radio_button" &&
                node.variable.startsWith(w.variable + "_")
            )
            if (owner) return false
        }
        return true
    })

    // build the tree: attach each node to its parent by variable
    const byVariable = {}
    for (const node of filtered) {
        byVariable[node.variable] = node
    }

    const roots = []
    const childrenMap = {}

    for (const node of filtered) {
        const parent = byVariable[node.parentVariable]
        if (parent && parent !== node) {
            if (!childrenMap[parent.variable]) childrenMap[parent.variable] = []
            childrenMap[parent.variable].push(node)
        } else {
            roots.push(node)
        }
    }

    for (const node of filtered) {
        node.children = childrenMap[node.variable] || []
    }

    // set the root (main window) layout based on how its children are laid out
    // (place / pack / grid), so loaded widgets render in the right container.
    const setRootLayouts = (nodes, parentLayout) => {
        for (const node of nodes) {
            if (node.layout && node.layout.type !== "place") {
                const root = node.parentVariable ? byVariable[node.parentVariable] : null
                if (root && root.widgetType === "main_window" && root.layout !== "flex") {
                    root.layout = { type: node.layout.type }
                }
            }
            if (node.children && node.children.length > 0) {
                setRootLayouts(node.children, node.layout)
            }
        }
    }
    setRootLayouts(roots)

    return { roots, widgets: filtered, rootVariable }
}
